// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANg8J67jpERXjNmLnSnvTpJqCIBZjh0qY',
    appId: '1:861551177604:android:41f491b65526bae2c5f7d1',
    messagingSenderId: '861551177604',
    projectId: 'my-notes-app-mittal',
    storageBucket: 'my-notes-app-mittal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYfb5uHZjIDMA7c2jA3bzfrphSyb356Aw',
    appId: '1:861551177604:ios:2e274ab1d8dd0b60c5f7d1',
    messagingSenderId: '861551177604',
    projectId: 'my-notes-app-mittal',
    storageBucket: 'my-notes-app-mittal.appspot.com',
    iosClientId: '861551177604-3rm1o7kb2koas480bta7bc13i3bm9aql.apps.googleusercontent.com',
    iosBundleId: 'com.hirdey.mittal',
  );
}
